"""add_challenge_tables

Revision ID: 035550a2394e
Revises: 8fb0f96b9eb9
Create Date: 2024-11-17 18:32:25.959804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035550a2394e'
down_revision = '8fb0f96b9eb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
